import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { ICONS, NAV, T, Icon, Btn, Card, Badge, Input, Select, Field, SectionHeader, EmptyState, Modal, StatCard, UtilArc } from './ui.jsx';
import { uid, fmt, fmtCurrency, parseCsvParts, blankDraft, SEED_MATERIALS, SEED_STANDARD_PARTS } from '../utils/helper.js';
import { downloadDxf, parseDxfDimensions } from '../utils/dxfExport.js';
import { runOptimization, runGeneticOptimizationAsync, packSecondaryParts, collectScrapCandidates, aiQualityScore, aiAutoSelectAlgorithm, breakdownBySize } from '../utils/nestingAlgorithm.js';
import { storeGet, storeSet, storeDelete, cloudSave, cloudLoad } from '../services/storage.js';

export function JobReportModal({
  chosen,
  draft,
  material,
  onClose
}) {
  const ai = aiQualityScore(chosen);
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>ISNS Job Report — ${draft.jobNo}</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#1a1a2e;} h1{color:#1e3a8a;} table{border-collapse:collapse;width:100%;} td,th{border:1px solid #ddd;padding:8px;font-size:13px;} th{background:#1e3a8a;color:#fff;text-align:left;} .badge{display:inline-block;padding:2px 8px;border-radius:3px;font-weight:bold;} .good{color:green;} .warn{color:orange;} .bad{color:red;}</style></head><body><h1>ISNS AI Enterprise — Nesting Job Report</h1><p><strong>Job No:</strong> ${draft.jobNo} &nbsp; <strong>Project:</strong> ${draft.project || '—'} &nbsp; <strong>Customer:</strong> ${draft.customer || '—'}</p><p><strong>Date:</strong> ${new Date().toLocaleDateString()} &nbsp; <strong>AI Quality:</strong> <span class="${ai.score >= 80 ? 'good' : ai.score >= 60 ? 'warn' : 'bad'}">${ai.grade} (${ai.score}/100)</span></p><hr/><h2>Material</h2><table><tr><th>Material</th><th>Grade</th><th>Thickness</th><th>Supplier</th></tr><tr><td>${material.name}</td><td>${material.grade}</td><td>${material.thickness}mm</td><td>${material.supplier || '—'}</td></tr></table><h2>Results</h2><table><tr><th>Total Sheets</th><th>Fresh</th><th>Scrap Reused</th><th>Utilization</th><th>Scrap %</th><th>Material Cost</th></tr><tr><td>${chosen.sheetsUsed}</td><td>${chosen.freshSheetsUsed ?? chosen.sheetsUsed}</td><td>${chosen.scrapSheetsUsed || 0}</td><td>${fmt(chosen.utilization, 1)}%</td><td>${fmt(chosen.scrapPct, 1)}%</td><td>₹${fmt(chosen.cost, 0)}</td></tr></table><h2>Parts</h2><table><tr><th>Part No</th><th>Shape</th><th>L × W (mm)</th><th>Qty</th><th>Priority</th></tr>${draft.parts.map(p => `<tr><td>${p.partNo}</td><td>${p.shapeType || 'rectangle'}</td><td>${p.length} × ${p.width}</td><td>${p.qty}</td><td>${p.priority}</td></tr>`).join('')}</table><p style="margin-top:30px;font-size:12px;color:#888;">Generated by ISNS AI Enterprise &middot; ${new Date().toLocaleString()}</p></body></html>`;
  const download = () => {
    const blob = new Blob([html], {
        type: 'text/html'
      }),
      url = URL.createObjectURL(blob),
      a = document.createElement('a');
    a.href = url;
    a.download = `ISNS_Report_${draft.jobNo}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  return <Modal title={`Job Report — ${draft.jobNo}`} onClose={onClose} wide>
      <div style={{
      background: T.panel,
      borderRadius: 8,
      padding: 16,
      marginBottom: 16,
      fontSize: 13,
      color: T.textDim,
      lineHeight: 1.8
    }}>
        <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: 8
      }}>
          <div><b style={{
            color: T.textMuted
          }}>Job No:</b> <span style={{
            color: T.text,
            fontFamily: T.fontMono
          }}>{draft.jobNo}</span></div>
          <div><b style={{
            color: T.textMuted
          }}>Project:</b> <span style={{
            color: T.text
          }}>{draft.project || '—'}</span></div>
          <div><b style={{
            color: T.textMuted
          }}>Customer:</b> <span style={{
            color: T.text
          }}>{draft.customer || '—'}</span></div>
          <div><b style={{
            color: T.textMuted
          }}>Date:</b> <span style={{
            color: T.text
          }}>{new Date().toLocaleDateString()}</span></div>
          <div><b style={{
            color: T.textMuted
          }}>Material:</b> <span style={{
            color: T.text
          }}>{material.name} · {material.grade} · {material.thickness}mm</span></div>
          <div><b style={{
            color: T.textMuted
          }}>AI Quality:</b> <span style={{
            color: aiQualityScore(chosen).color,
            fontWeight: 700
          }}>{aiQualityScore(chosen).grade} ({aiQualityScore(chosen).score}/100)</span></div>
        </div>
      </div>
      <div style={{
      display: 'grid',
      gridTemplateColumns: 'repeat(4,1fr)',
      gap: 8,
      marginBottom: 16
    }}>
        {[{
        l: 'Sheets Used',
        v: chosen.sheetsUsed,
        c: T.blue
      }, {
        l: 'Utilization',
        v: `${fmt(chosen.utilization, 1)}%`,
        c: T.green
      }, {
        l: 'Scrap',
        v: `${fmt(chosen.scrapPct, 1)}%`,
        c: T.orange
      }, {
        l: 'Material Cost',
        v: fmtCurrency(chosen.cost),
        c: T.text
      }].map(m => <div key={m.l} style={{
        background: T.card,
        borderRadius: 8,
        padding: 12,
        textAlign: 'center',
        border: `1px solid ${T.border}`
      }}>
            <div style={{
          fontFamily: T.fontDisplay,
          fontSize: 20,
          fontWeight: 700,
          color: m.c
        }}>{m.v}</div>
            <div style={{
          fontSize: 11,
          color: T.textMuted,
          textTransform: 'uppercase',
          marginTop: 4
        }}>{m.l}</div>
          </div>)}
      </div>
      <div style={{
      display: 'flex',
      justifyContent: 'flex-end',
      gap: 8
    }}>
        <Btn variant="ghost" onClick={onClose}>Close</Btn>
        <Btn icon="report" onClick={download}>Download HTML Report</Btn>
      </div>
    </Modal>;
}

/* ════════════════════════════════════════
   JOBS HISTORY
════════════════════════════════════════ */
export function JobsPanel({
  jobsIndex,
  onOpen,
  onDelete
}) {
  return <div className="slide-up">
      <SectionHeader eyebrow="History" title="Saved Jobs" />
      {jobsIndex.length === 0 ? <Card><EmptyState title="No saved jobs" body="Run and save a nesting job to build your production history." /></Card> : <div style={{
      display: 'flex',
      flexDirection: 'column',
      gap: 8
    }}>
          {jobsIndex.map(j => <Card key={j.id} style={{
        display: 'flex',
        alignItems: 'center',
        gap: 12
      }}>
              <div style={{
          width: 40,
          height: 40,
          borderRadius: 8,
          background: `${T.blue}18`,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          flexShrink: 0
        }}><Icon d={ICONS.folder} size={16} color={T.blue} /></div>
              <div style={{
          flex: 1,
          minWidth: 0
        }}>
                <div style={{
            fontSize: 14,
            fontWeight: 600,
            color: T.text
          }}>{j.jobNo} · {j.project || 'Untitled'}</div>
                <div style={{
            fontSize: 12,
            color: T.textMuted
          }}>{j.materialName} · {j.sheetSize} · {j.sheetsUsed} sheets · {fmt(j.utilization, 1)}% · {new Date(j.createdAt).toLocaleDateString()}</div>
              </div>
              <span style={{
          fontFamily: T.fontMono,
          fontWeight: 700,
          color: T.green,
          fontSize: 13
        }}>{fmtCurrency(j.cost)}</span>
              <Btn size="sm" variant="ghost" onClick={() => onOpen(j.id)}>Open</Btn>
              <button onClick={() => onDelete(j.id)} style={{
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          color: T.red
        }}><Icon d={ICONS.trash} size={14} /></button>
            </Card>)}
        </div>}
    </div>;
}

/* ════════════════════════════════════════
   SCRAP INVENTORY
════════════════════════════════════════ */